server {
  listen 80;

  location /externel-psp/ {
    root /usr/share/nginx/html/;
    include /etc/nginx/mime.types;
    try_files $uri $uri/ /externel-psp/index.html;
  }

  location / {
    root /usr/share/nginx/html/externel-psp/;
    include /etc/nginx/mime.types;
    try_files $uri $uri/ /index.html;
  }
}
